export type TemplateType = 'offer' | 'contract' | 'invoice' | 'receipt' | 'nda' | 'brief' | 'reminder' | 'custom';

export interface BrandingSettings {
  showHeader: boolean;
  logo?: string;
  headerText?: string;
  headerAlignment: 'left' | 'center' | 'right';
  headerHeight: number;
  showFooter: boolean;
  footerText?: string;
  footerAlignment: 'left' | 'center' | 'right';
  fontFamily: string;
  fontSize: number;
  lineHeight: number;
  primaryColor: string;
  textColor: string;
  backgroundColor: string;
  headerFooterBgColor?: string;
  margins: {
    top: number;
    bottom: number;
    left: number;
    right: number;
  };
}

export const DEFAULT_BRANDING: BrandingSettings = {
  showHeader: true,
  headerAlignment: 'left',
  headerHeight: 100,
  showFooter: true,
  footerText: 'Generated by Auxilium CRM',
  footerAlignment: 'center',
  fontFamily: 'Inter',
  fontSize: 13,
  lineHeight: 1.5,
  primaryColor: '#0A0A0A',
  textColor: '#0A0A0A',
  backgroundColor: '#FFFFFF',
  margins: { top: 20, bottom: 20, left: 20, right: 20 }
};
