import type { Metadata } from "next";
import { Inter, Anonymous_Pro } from "next/font/google";
import { Toaster } from "sonner";
import { UserProvider } from "./context/UserContext";
import Navbar from "./components/Navbar/Navbar";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

const anonymus_pro = Anonymous_Pro({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--anonymus-pro",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Auxillium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pl"
      className={`${inter.className} ${anonymus_pro.variable} h-full antialiased`}
      suppressHydrationWarning={true}
    >
      <body className="min-h-full flex flex-col">
        <UserProvider>
          {children}
        </UserProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}

