import puppeteer from 'puppeteer';
import { BrandingSettings } from '@/actions/templates';
import { marked } from 'marked';

export async function generatePDF(htmlContent: string, branding: BrandingSettings) {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  const page = await browser.newPage();

  // Construct full HTML with styles
  const fullHtml = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Roboto:wght@400;700&family=Merriweather:wght@400;700&family=Playfair+Display:wght@400;700&display=swap" rel="stylesheet">
      <style>
        body {
          font-family: '${branding.fontFamily}', sans-serif;
          font-size: ${branding.fontSize}px;
          line-height: ${branding.lineHeight};
          color: ${branding.textColor};
          background-color: ${branding.backgroundColor};
          margin: 0;
          padding: 0;
        }
        .container {
          padding: ${branding.margins.top}mm ${branding.margins.right}mm ${branding.margins.bottom}mm ${branding.margins.left}mm;
        }
        h1 { color: ${branding.primaryColor}; font-size: 2.5em; margin-bottom: 0.5em; }
        h2 { color: ${branding.primaryColor}; font-size: 1.8em; margin-top: 1.5em; margin-bottom: 0.5em; border-bottom: 1px solid ${branding.primaryColor}20; padding-bottom: 0.2em; }
        h3 { font-size: 1.4em; margin-top: 1.2em; margin-bottom: 0.4em; }
        p { margin-bottom: 1em; text-align: justify; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 1.5em; }
        th { background-color: ${branding.primaryColor}05; border: 1px solid #E5E5E5; padding: 10px; text-align: left; font-weight: bold; }
        td { border: 1px solid #E5E5E5; padding: 10px; }
        .header { 
          margin-bottom: 30px; 
          text-align: ${branding.headerAlignment};
          border-bottom: 1px solid ${branding.primaryColor}20;
          padding-bottom: 20px;
        }
        .footer {
          position: fixed;
          bottom: ${branding.margins.bottom}mm;
          left: ${branding.margins.left}mm;
          right: ${branding.margins.right}mm;
          text-align: ${branding.footerAlignment};
          font-size: 10px;
          color: #A1A1AA;
          text-transform: uppercase;
          border-top: 1px solid ${branding.primaryColor}20;
          padding-top: 10px;
        }
        @media print {
          .page-break { page-break-before: always; }
        }
      </style>
    </head>
    <body>
      <div class="container">
        ${branding.showHeader ? `
          <div class="header">
            ${branding.logo ? `<img src="${branding.logo}" style="max-height: 60px; margin-bottom: 10px;">` : ''}
            <div style="font-size: 12px; color: #71717A; white-space: pre-wrap;">${branding.headerText || ''}</div>
          </div>
        ` : ''}
        
        <div class="content">
          ${htmlContent}
        </div>

        ${branding.showFooter ? `
          <div class="footer">
            ${branding.footerText || 'Generated by Auxilium CRM'}
            <div style="margin-top: 4px;">Strona <span class="pageNumber"></span> z <span class="totalPages"></span></div>
          </div>
        ` : ''}
      </div>
    </body>
    </html>
  `;

  await page.setContent(fullHtml, { waitUntil: 'networkidle0' });
  
  const pdfBuffer = await page.pdf({
    format: 'A4',
    printBackground: true,
    margin: {
      top: 0,
      bottom: 0,
      left: 0,
      right: 0
    },
    displayHeaderFooter: false // We use our own fixed divs for footer simulation or real headers if needed
  });

  await browser.close();
  return pdfBuffer;
}

export async function markdownToHtml(markdown: string) {
  return marked.parse(markdown);
}
